/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
export module ui {
    export class scaleUI extends laya.display.EffectAnimation {
		public ani1:Laya.FrameAnimation;
        public static  uiView:any ={"type":"View","props":{},"compId":2,"child":[{"type":"Image","props":{"y":0,"x":0,"skin":"comp/image.png"},"compId":4}],"animations":[{"nodes":[{"target":4,"keyframes":{"x":[{"value":0,"tweenMethod":"linearNone","tween":true,"target":4,"key":"x","index":0}],"scaleY":[{"value":1,"tweenMethod":"linearNone","tween":true,"target":4,"key":"scaleY","index":0},{"value":0.5,"tweenMethod":"linearNone","tween":true,"target":4,"key":"scaleY","index":4}],"scaleX":[{"value":1,"tweenMethod":"linearNone","tween":true,"target":4,"key":"scaleX","index":0},{"value":0.5,"tweenMethod":"linearNone","tween":true,"target":4,"key":"scaleX","index":4}]}}],"name":"ani1","id":1,"frameRate":24,"action":0}],"loadList":["comp/image.png"],"loadList3D":[]};
        constructor(){ super();this.effectData =ui.scaleUI.uiView;}
    }
}
export module ui.Scene {
    export class MainSceneUI extends Laya.Scene {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Scene/MainScene");
        }
    }
}
export module ui.test {
    export class TestSceneUI extends Laya.Scene {
		public scoreLbl:Laya.Label;
		public tipLbll:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/TestScene");
        }
    }
}